version: "2"
services:
  frontend:
    volumes:
      - ./frontend:/usr/www
  backend:
    volumes:
      - ./backend:/usr/www
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
  data:
    build: ./data
    links:
      - mongo
