version: "2"
services:
  backend:
    container_name: reaccounts-backend
    restart: always
    build: ./backend
    ports:
      - "8000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
