version: "2"
services:
  frontend:
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/src:/usr/www/src
      - ./frontend/config:/usr/www/config
  backend:
    volumes:
      - ./backend:/usr/www
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
  data:
    build: ./data
    restart: on-failure
    links:
      - mongo
