version: "2"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
  backend:
    container_name: reaccounts-backend
    restart: always
    build: ./backend
    ports:
      - "3001:3000"
    links:
      - mongo
  frontend:
    container_name: reaccounts-frontend
    restart: always
    build: ./frontend
    ports:
      - "8000:3000"
    links:
      - backend
    volumes:
      - ./public:/usr/www/public
