version: "2"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    command:
      - "--syslog"
  backend:
    container_name: reaccounts-backend
    restart: always
    build: ./backend
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - ./public:/usr/www/public
  frontend:
    container_name: reaccounts-frontend
    restart: always
    build: ./frontend
    ports:
      - "8000:8000"
    links:
      - backend
    volumes:
      - ./public:/usr/www/public
      - ./dist:/usr/www/dist
